- main.lua
`posY` was changed into a function to dynamically return the position.
`modifiedPosY` was introduced for when the code detects the player has the school bag and needs to move the hud down.
> Fix EIDConfig["YPosition"] not working

- descriptions/ab+/en_us.lua
Changed "him" to "you", as it's more in line with other descriptions and is better suitable for all characters
> Update description of Purity

- descriptions/ab+/en_us.lua
Updated Taurus description to include -0.3 Speed down
> Updated Taurus description

- descriptions/ab+/pt_br.lua
- descriptions/rep/pt_br.lua
- Correction of some words
- Remaining horsepills translated
- Golden trinket translated
- Bag of Crafting translated
> Update PT-BR translation

- main.lua
It solves the issue #110.
We can compare a pickup's sprite with the questionmark sprite to determine if it is hidden in alt-path.
If the player has Glitched Crown, and there are too many items in the room, it will costs too much cpu, so don't check every items.
> Use sprite color to detect hidden items in alt path

- main.lua
Update check so it renders while in "Visuals" tab of EID
> Render when in "Visuals" tab of EID

- descriptions/rep/en_us.lua
- eid_modifiers.lua
This adds support for the new Book of Belial interactions with Judas' Birthright.
> Add Book of Belial modifier for Judas' Birthright

- eid_api.lua
reported in steam comments (i'm gonna try to keep an eye on them)
> Fix crash on TMTRAINER + spindown dice

- eid_api.lua
- eid_config.lua
- eid_debugging.lua
- main.lua
- mod_config_menu.lua
Add Local Mode render in config and Mod Config Menu. These are not all the changes that I would like to implement, but a working one that can be modified is already available. The previous time I just laid out the whole folder from my storage which was a mistake
> Add LocalMode render

- descriptions/rep/spa.lua
sorry for what i did with binge eater last time
> Warning changes and some pills names

- main.lua
am dumb, this breaks if you have flight because pathchecker is always nil then
> revert trying to fix frame of non-obstruction

- descriptions/rep/spa.lua
Mostly additions of new information about BoV and Abyss, along with some minor fixes.
> Updates to spanish descriptions

- README.md
We've created a Discord server for all mods & modding docs by wofsauge.
If you want to join and chat, help, get some quick support, feel free!
You can click on the discord widget to join or alternatively use this link: https://discord.gg/435qCC6nHt
> Add download and discord widgets

- descriptions/ab+/en_us.lua
- main.lua
> Fix Curse of the Blind + Show Alt Path interaction

- eid_config.lua
- eid_data.lua
Only comments and formatting were changed.
> Improve config comments

- resources/gfx/eid_inline_icons.anm2
I made the mistake of not testing them before in AB+, I did and they were a little bit wrongly organized so I readjusted them.
I leave the .anm2 and the .png because I don't know if both are needed.
> Fixed the position of stats icons in AB+

- descriptions/rep/spa.lua
I added what is used descriptions of glitched items 
Tarot Cloth buffs (for some reason they were missing)
And a few other things
> Added some things

- content/entities2.xml
- main.lua
It has potential issues
It's going to be better to just lower how frequently the pathchecker exists
> Revert pathchecker change

- descriptions/ab+/zh_cn.lua
- descriptions/rep/zh_cn.lua
- Just update for new Void feature.
> zh_cn : updates for Void feature

- descriptions/ab+/spa.lua
Unfortunately my PC doesn't seem to support .NET 6 or higher so I can't test this, if someone can do it for me I would be very grateful
> Added a translation for the savefile reader advice

- descriptions/ab+/zh_cn.lua
- descriptions/rep/zh_cn.lua
- Corrected names of some pills.
- Added collection page info text.
> zh_cn : update for sync and fix

- eid_api.lua
- main.lua
- mod_config_menu.lua
A little messier in the API to get the text color callback / sprite frame data, but all colors and animated icons look to be working now
> Cache previous description (with animated text color / icon support)

- eid_api.lua
- Fixed EID:removeDescriptionModifier function not working
- Made EID:addDescriptionModifier function update existing modifier, to prevent multiple modifiers with same name
> Fix modifier issues

- scripts/LEEME.txt
I figured this would be something useful
> Translated README.txt

- eid_api.lua
- eid_modifiers.lua
- main.lua
Its better to make this stuff public so people can add description modifiers easier without recreating a lot of it with their own systems.
A mod I'm currently making (a Spinup Dice) requires it
> Make some modifier stuff global and add saving

- eid_api.lua
- eid_modifiers.lua
- main.lua
I have no clue how mine and kittenchilly's requests were both acceptable without conflicts, I incorporated those changes into mine already
> fix modifiers stuff in two places

- descriptions/ab+/en_us.lua
- eid_data.lua
- eid_holdmapdesc.lua
- eid_itemprediction.lua
- main.lua
and a pickup name table to localize if anyone wants to for this niche cheat feature...
> D1 prediction

- eid_bagofcrafting.lua
Fixes Bag of Crafting for v1.7.9
> Use CraftingQuality instead of Quality

- descriptions/ab+/spa.lua
- descriptions/rep/spa.lua
ok so there is it, spanish pack fully updated
> spa: updated spanish descriptions 

- CREDITS.md
just added myself to spanish credits
ok and changed a little bit english ones
> updated CREDITS.md

- eid_modifiers.lua
From disassembly. It probably doesn't matter but I think its good to have them just in case?
> More accurate magic numbers for consolation prize calculation

- descriptions/ab+/ko_kr.lua
- descriptions/rep/ko_kr.lua
- Fix Gimpy (wrong luck)
- Fix Book of Revelations (more clarification)
- Shorten length for BoC recipe strings
> ko_kr : Some fixes

- descriptions/rep/ko_kr.lua
- eid_tmtrainer.lua
- update ko_kr entries
- moved on use effect to below granted item(given effect regardless of on use)
> small TMTRAINER updates

- descriptions/rep/en_us.lua
- eid_modifiers.lua
Regarding #564 
I've added a callback function for Glowing Hourglass. Let me know if it can be improved.
> Update Glowing Hourglass description when it is depleted

- descriptions/ab+/ko_kr.lua
- descriptions/rep/ko_kr.lua
> ko_kr : sync with en_us

- descriptions/ab+/de.lua
- descriptions/ab+/en_us.lua
- translated de to item 169
- updated de with tear delay multiplier naming
- upadted en_us with tear delay multiplier naming and small changes
> translated to 169 + en_us update

- descriptions/ab+/en_us.lua
- descriptions/rep/en_us.lua
- features/eid_conditionals.lua
Added conditional to replace mentions of red hearts with soul/black/coin hearts for characters that use them
> conditional for heals for characters with no red health

- descriptions/ab+/en_us.lua
- descriptions/rep/en_us.lua
- eid_config.lua
- features/eid_api.lua
- features/eid_bagofcrafting.lua
- features/eid_conditionals.lua
- features/eid_data.lua
- features/eid_mcm.lua
- features/eid_modifiers.lua
Add a Tainted Cain pedestal salvage modifier
Add more Tainted Bethany conditionals for outliers like Isaac's Fork
Prevent learning recipes before making them when Curse of the Blind is active
Fix Dice Room co-op conditionals (forgot to test them, subtype needed offsetting by 1)
Fix the health up modifier not saying when item has different effect for non-red players
> Salvage modifier + misc

- features/eid_data.lua
- features/eid_modifiers.lua
HealingRed lines removal for custom health types support
> Dynamic health "{{HealingRed}}" lines removal list

- main.lua
this fixes the slot borders and highlights being misplaced
> position offset is taken into account for indicators

- main.lua
In testing this fixes Bag of Crafting and probably some other stuff.
> Fix Rep+ XMLData not applying

- features/eid_modifiers.lua
Have Consolation Prize use EID:getPlayerName instead of directly using player:GetName()
> Consolation Prize player name fix

- features/eid_api.lua
Allows modders to include a copy of eid_api file in their mods to get autocompletion with Sumneko Lua VSCode extension. 
- Documented function params and returns to the best of my understanding.
- Modified some functions to add return values where it makes sense (for example, EID:PlayerHasCard would return nil if no player has a card, it now returns false).
- Added class annotations/aliases for some commonly used structures such as DescriptionObject or Icon.
> Added Luadoc comments to all functions in eid_api.lua

- descriptions/ab+/en_us.lua
fix minor grammar issue, add info about enemies also exploding if poisoned
> Better Contagion description

- features/eid_api.lua
Currently, any descriptions added, notably under EID:addEntity, do not account for subtypes of -1 that would encompass all subtypes of that type-variant combination. I made a fix by adding a check under EID:getDescriptionEntry, since everything allowing descriptions to render points back to this function. Subtypes of 0 would still need to be explicitly defined
> -1 SubType description fix

- features/eid_api.lua
- main.lua
Crane Game wasn't displaying the description at all, so I fixed that and also improved it using repentogon.
> Fix Crane Game description, add REPENTOGON support

- .github/scripts/lookuptable_generator.py
- descriptions/ab+/en_us.lua
- descriptions/rep+/en_us.lua
Based on the Judgement rewrite.
> Wheel of Fortune Rewrite

- resources/gfx/eid_inline_icons.anm2
Wasn't in the ANM2 for some reason
> Fix Death Mark icon
