descriptions/ab+/de.lua
descriptions/ab+/en_us.lua
descriptions/ab+/turkish.lua

Changed "dragable" to "Draggable".
I'm unsure if this is synced anywhere. I'm happy to fix at the source if this is the case.

Fix typo on Samson's Chains

---

descriptions/ab+/en_us.lua

Just caught that while playing, I believe `change` was supposed to be `chance` there.

Fix typo on daemon's tail description

---

eid_api.lua

This text is rendered incorrectly:  
```
Test: ABC{{ColorGray}}DEF{{ArrowUp}}
```

add offsetX when render inline icons

---

eid_api.lua

This text is not rendered correctly, because `textPart[3]` does not filter out inline icons.
```
Test:{{ArrowUp}}ABC{{ColorGray}}DEF
```

Fixed the rendering width of text that containing inline icons

---

eid_api.lua

The `scale`  was ignored incorrectly in commit [5be3b82](https://github.com/wofsauge/External-Item-Descriptions/commit/5be3b8260cf47b3a88a3b8532b37b9f9cf3692af).

Fixed wrong offset when rendering scaled text

---

descriptions/ab+/en_us.lua

The Era Walk card was displaying `↓ -0.5 Speed down` instead of `↑ +0.5 Speed up` in `en_us.lua`.
`en_us_detailed.lua` displays the correct description.

Update Era Walk description (ab+/en_us.lua)

---

mod_config_menu.lua

Replaced `Qualtiy` with `Quality` on the "Visuals" page.

Fixed typo in Mod Config Menu

---

eid_api.lua
eid_data.lua

Instead of a set table of IDs to skip, it now uses the vanilla rules of skipping items (if it exists and is not tagged as "hidden" in itemconfig). This should make it properly work with modded items and also be futureproof.

Better Spindown Dice method

---

main.lua

Creates a helper function (since the code is used twice) that sets the player to the soul if the main player is the forgotten to resolve #76

Find entities closest to the soul when playing as tainted forgotten

---

descriptions/ab+/en_us.lua

I changed the names for Lord of the Flies to Beelzebub and Mom to Yes Mother?, which broke the transformation icons. Unless there's an easier fix for this, I'm reverting the change as not only it should be fixed, it should be implemented across all localization files (where there's no localized names for those transformations).

Revert transformation names

---

descriptions/rep/en_us.lua
eid_api.lua
eid_bagofcrafting.lua
main.lua

I'm not sure if there's false positives with the check, but the reception has been negative, and the warning doesn't really help people figure out how to fix it (if they even want to fix it)
I think there's a massive epidemic of people with broken mods from items/sounds.xml overwrites right now, and well, I sure hope they don't try to beat Mother, but I guess it's better to just stay out of it
I added a couple extra collectible = nil checks to the functions that were tending to cause issues

remove the low max item count warning message

---

eid_bagofcrafting.lua
eid_config.lua
main.lua

I did testing of how many milliseconds each part of the crafting algorithm takes, and was surprised (but glad) to find that the actual recipe result calculation is by far the slowest part, rather than the combination / random pull steps
I noticed that stupidly I wasn't caching recipe results unless they were on a locked item, and adding that caching indeed greatly reduces recipe crunching time as it builds a database (in testing, it may start at 130ms, and go down to 20ms after a few refreshes)
I tested switching to local XML tables in the file, but didn't see any speed increase, which I'm glad for cause I quite like having the pool and quality info outside of the code file
I also added a little warning on the config version
Hopefully I'm done for a bit :)

Improve recipe caching

---

eid_api.lua
eid_config.lua
main.lua
mod_config_menu.lua

Gets what item the crane game should have using POST_GET_COLLECTIBLE. Saves data of the item's type to the crane game and updates depending on what happens to the machine. Displays the item description of the item type in the data.
Basically just makes items inside the crane game have their descriptions show up. Maybe there'll be a better method once we get actual slot support in the API.
Also includes a new config option to enable or disable this.

Support items inside Crane Game

---

descriptions/rep/spa.lua

When I was copying things I left out the pluralizer, and I copied it, which I just noticed

Fixed an error with glitched items descriptions

---

eid_api.lua
eid_tmtrainer.lua
main.lua

Used a combination of InitSeed and GridIndex to be able to keep track of our flippable pedestals much better, hopefully without any performance decrease. (It double-checks every pedestal's grid index each time a collectible is spawned, but I don't see any lag spike even with 100 collectibles in a room)
As far as my testing goes, it now works with Damocles, works with Mr. ME!, works with restocking shops, works with D6, works with Tainted Isaac / Glitched Crown, works with dropping Flip in a room or dropping and exiting and re-entering rooms
The only bug I'm aware of is that re-entering a room that used to have a pedestal, so nothing is spawned there now, and spawning a pedestal in its gridindex will make it will think it's flippable. (Doesn't seem worth the milliseconds to fully delete …

More Flip improvements

---

descriptions/rep/en_us.lua
eid_tmtrainer.lua
main.lua

* Prevent Diplopia pedestals from showing Flip descriptions (...until you re-enter the room, but fixing that would get too complicated)
* Glitched item descriptions now check the log only when a new glitched item has spawned rather than when you have TMTRAINER (less log checks + works with Corrupted Data glitched items)
* Moved glitched item color data to the tmtrainer lua file (localizations would get desynced and be harder to make)
* Made effect triggers have more fitting colors than cyan to help tell them apart even more
* Up/Down arrows for the Heart/Pickup stats

Corrupted Data support, fix Diplopia + Flip

---

descriptions/ab+/en_us.lua
descriptions/ab+/ko_kr.lua
descriptions/ab+/zh_cn.lua
eid_api.lua
eid_data.lua
main.lua
mod_config_menu.lua

Chinese text does not use spaces as separators, so it cannot be automatically wrapped by spaces. This algorithm wraps lines between utf8 characters to solve the problem.
I also removed some string concat operations, it may makes the algorithm time complexity O(n), where n is the length of the string.
Some languages should not break between utf8 characters, so I added `EID.BreakUtf8CharsLanguage` to configure it.
And this algorithm does not eliminate consecutive spaces, which is different from the old algorithm.

add utf8 support for EID:fitTextToWidth

---

content/entities2.xml
descriptions/ab+/en_us.lua
main.lua

* Replace unique EID pathfinder entity with an Ultra Greed Door
* This fixes the pathfinder entity being replaceable by Glitched Item effects, and enabling/disabling EID making suspended games uncontinuable
* Fix Knife Piece 1 pedestal not displaying its Flip item description
* Fix a blank markup in Puberty description
I saw absolutely no glitches or changes from making this pathfinder change in all my misc. testing and a full run to Beast. Ultra Greed/Greedier do not react to it because they create children doors that they mess with. If there's some incompatible mod out there that does weird things to all Ultra Greed Doors, well, there'll be ways around it.'
I haven't tested AB+ at all recently but I purposely chose a AB+ compatible entity and I can't see a reason this would affect AB+ …

Use Ultra Greed Door as pathfinder entity

---

main.lua

Pathfinding is now initiated by pills/cards, rather than in an update.
The entity is created if necessary, does one pathfind check, and is then removed. This should fix non-vanilla effects like Suplexing the pathfinder, glitched items replacing the pathfinder with a different entity, disabling EID making it turn into a shopkeeper, etc.
Theoretically there'd be little harm in making it a regular shopkeeper or other NPC now (I'd still like EID to not have a "content" folder...). I don't know what mods out there do something with seeing Shopkeepers spawn in MC_PRE_ENTITY_SPAWN, although if they just look for type 17, they'd be doing it to the custom pathfinder anyway. But I'll leave that for you to decide.
Positive results are stored in the entity's GetData, so true results mean no more …

Pathfinding overhaul + performance improvements

---

descriptions/ab+/en_us.lua
descriptions/rep/en_us.lua
eid_config.lua
eid_modifiers.lua
eid_tmtrainer.lua
main.lua
mod_config_menu.lua

* Add a "Map" text to the "hold map button for preview" text (since it doesn't support non-default control mapping)
* Add the hold to preview feature to Spindown Dice
* Remove F5 being a default hotkey for the Scale toggle, since everyone keeps hitting it by accident and having no clue what to do
* Fix Glitched Item Descriptions + Glowing Hour Glass bug
* Fix Flip item descriptions not showing right after game load
* Allow entities to get an immediate pathfind check if they've never attempted one before
* Add a basic Void / Black Rune stat increase preview for 1 pedestal's worth of stats; lots of things to improve about it but I wanted to get these bug fixes in
* Started a bit of Mod Config Menu file overhaul while adding the new Void option

Void stat increase preview 1.0 + misc

---

eid_api.lua
eid_bagofcrafting.lua
eid_modifiers.lua
main.lua

* Overhaul the pickup detection, much more immediately responsive and fixes some bag content desyncs
* Use coroutines to not drop frames while recipe crunching
* Save the object names to make the initial table sort much shorter
* Fix No Recipes Mode being broken
* Include the player's held cards/pills when tallying up the floor's pickups
* Cache the most recent Bag description text to be reused if nothing's changed since the previous frame

Bag of Crafting massive performance improvement

---

content/items.xml
descriptions/rep/en_us.lua
main.lua

Adds a dummy trinket that has the womb unlock achievement attached to it. It then uses RemoveTrinkets on it to check if its unlocked or not and to prevent it from being available in-game. This should work 100% of the time, and if it breaks its the fault of another mod.

Add full proof check for if achievements are enabled

---

eid_api.lua
main.lua

I had no clue GetAnimation was a Rep-only function. Luckily, with the frame-info-passthrough I had to do for animated icons to work, I don't actually need that function anymore, as long as every renderIcon that might get cached passes in its anim name/frame.

Fix description caching failing on AB+

---

main.lua

If you continued a run before, it didn't save the status of achievements so it'd show the achievements are disabled notice even if they actually are enabled. This fixes that by making the status save, and it only set it on new run.

Save achievementsEnabled status

---

main.lua

It shouldn't be in the pool, but if it somehow does spawn i.e. from the pool being reset, it'll morph into another random trinket.

Add failsafe to prevent achievement helper trinket from spawning

---

eid_api.lua
eid_config.lua
eid_data.lua
main.lua
mod_config_menu.lua

Added a language called `auto`. If available, EID will use the language in the Options menu to determine its display language.

Add "auto" language

---

eid_api.lua
eid_modifiers.lua

- Added EID:addCardMetadata, EID:addPillMetadata functions. This modifies tables from eid_xmldata.lua tables, but will allow modded cards/runes/pills to add Blank Card/Clear Rune/Placebo charges without making their own modifiers.
- EID:addPillMetadata also allows adding False PHD effects for modded pills, but custom effects for False PHD still needs to be added through their own modifiers.
- Made blankCardHidden, runeIDs tables in eid_modifiers.lua global, to make these function possible.

Added 'addMetadata' API functions

---

eid_config.lua

This better fits how Bag of Crafting now works and feels less cheaty for people that run the mod as is without MCM.

Change default Bag of Crafting display mode to No Recipes

---

eid_bagofcrafting.lua
main.lua

* Fix outdated mods setting the REPENTANCE constant to false, breaking rep-only EID features (item quality, alt path item hiding) and who knows what else
* Fix Bag of Crafting modded item checks unnecessarily reloading xml data; I wrote it to support mods changing in between game loads, but, EID will be reloaded from scratch if your loaded mods change anyway!

Fix mods making REPENTANCE = false

---

eid_api.lua
eid_modifiers.lua

This adds an API function for an easy-ish way for modded trinkets to have appended text when doubled/tripled, or multiplying a number in their description, which should be the majority of use cases.
And a function to directly add a data table if someone wants the full functionality.
Also, color markup is now filtered out when checking for bulletpoint icons, since the Golden Trinket appended text starts with {{ColorGold}} and was preventing bulletpoint icons
Doing a pull request since my api function has a way bigger and more detailed comment than any other api function probably so maybe it shouldn't be that way

API function for adding Golden Trinket info

---

eid_api.lua
eid_bagofcrafting.lua

- Unfortunately, there are no such variables to read card type in `ItemConfigCard` class, _all modded runes will be also considered as cards_ instead of runes in EID. Modders should register their modded runes through `EID:addCardMetadata`.
- Modded objects are also considered as cards(Tested with Repentance + mod)
- Added a function to detect the certain playertype(just in case)

Fixed modded cards from EID BoC being considered as runes

---

eid_api.lua
main.lua

* Fix Dead Tainted Lazarus and Tainted Lazarus sharing the same actives/pills tracking
* Fix D4 looking at pocket items (counting Tainted Bethany's Lemegeton every usage)
* Fix starting active items not getting counted (Judas, ???, sometimes Eden)
* Fix the cached descriptions not updating when transformation progress changes
* Fix transformation progress display not working in co-op ("EID.players" table is actually only P1 and P1's Esau; "EID.coopAllPlayers" is what you wanted; I'd agree that EID.players should be changed to what you thought it was, would need careful refactoring)

Various transformation progress improvements

---

eid_api.lua
main.lua

- Fix descriptions not being appeared when repairing broken Crane Game machines through Glowing Hour Glass

Fix Crane Game + Glowing Hour Glass (again)

---

eid_api.lua
main.lua

Basically re-inits item interactions and the transformation table like it would when starting a new game.

Fix Genesis interaction

---

eid_api.lua
eid_data.lua

Adds an orange coloration to the number of crafting ingredients when the bag contains more than the required amount.
This makes it easier to see which items can be removed from the bag when trying to craft a specific item.
Note how the number for red hearts in the crafting receipe for the Butter Bean is orange because there's more than two hearts in the bag, indicating that hearts need to be removed.

Bag of Crafting item overfill color

---

main.lua

- Removed Magdalene + Birthright restriction for additional row for hearts
- Now will check heart containers + soul hearts count for row check. This fixes Keeper/T.Keeper health overlapping descriptions (example image below)

Adjusted offset for 3+ lines of hearts

---

eid_api.lua
eid_holdmapdesc.lua
eid_tmtrainer.lua
main.lua

* Change pill use tracking to track Pill Color, not Pill Effect (attempt to fix issues with pills that change their effect in context)
* Pill tracking is now a global table for all players, I don't think anyone playing co-op wants selective identifying of pill descs
* Fix bugs with Echo Chamber regarding tracking Gold Pills and card/pill usages that shouldn't get tracked
* Show specific Pill icon instead of the generic {{Pill}} for Echo Chamber
* Fix AB+ requiring MCM installed to save/load data
* Fix "EID.BoC" being nil in AB+
* add a silly April Fools joke for luadebug users since they have access to the computer's date

Pill Color tracking, Echo fixes, AB+ save fix

---

eid_mcm.lua
eid_mcm_cn.lua

This pull request add support for the [chinese version of MCM](https://steamcommunity.com/sharedfiles/filedetails/?id=2494192799).
I don't know where to put these texts, so I created a file called `eid_mcm_cn.lua`. Maybe it can be put somewhere else.
All it does is search and replace, so I don't think it will affect the normal work of EID, even if  `eid_mcm.lua` changes.

add support for MCM Chinese

---

main.lua

- Allows using Lemegeton display descriptions for wisps from Item Reminder. This shares with 'Recent Items'.
- No problems for T.Laz, and J&E, and usage with Car Battery/The Battery(quick use)/Void, although usage with Car Battery requires adjusting EID config settings(EID > Reminder > Recent Items (at least max 2))
https://user-images.githubusercontent.com/37092106/235313707-9d53ff5c-eae1-4497-8154-b8656114b8e7.mp4

Support Lemegeton Wisp for Item Reminder

---

eid_mcm.lua
eid_modifiers.lua
main.lua

- This doesn't change anything visually for normal circumstances. (now works like Transformation text, with line breaks)
- The reason of the change is to fix possible issues within callbacks, causing Last Pool name being ended up located in wrong position.
- Made EID:printBulletPoints function return render position to make this work better.

Changed location of last pool name function

---

eid_bagofcrafting.lua
eid_bagofcrafting_search.lua

Resolves #660 
This pull-requests adds the possibility to search available crafting recipes:
To start and finish a search one can use `Enter`.
These search queries can be locked using the regular locking combination `TAB + Shoot Left`.
After that you can't start a new search until you've unlocked the result display again.
Unlocking the result display will empty the search query.

Bag of Crafting: Search Function

---

eid_api.lua
eid_bagofcrafting.lua
eid_bagofcrafting_search.lua

I've made some changes to the search function's Enter input based on how I think it would control best.
I would like feedback from @CreepSore and anyone else about it, especially as I think he may have had something planned with EID.BoCSLockMode which currently is only 0.
Changes:
When not in search mode: Pressing Enter will both wipe your previous search, and start a new one
(In the future there can be two configurable hotkeys bound for these; for example Backspace to clear search, but Enter to start a new one / modify your previous one)
When in search mode: Pressing Enter will save your current search
Also, unlocking no longer wipes your current search; I think you may want to keep your search when unlocking
General improvements:
Do the item name check once per item ID rather than once …

BoC search changes/improvements

---

descriptions/rep/en_us.lua
eid_api.lua
eid_bagofcrafting.lua
eid_bagofcrafting_search.lua
eid_config.lua
eid_mcm.lua

Changes:
Added "Learned Recipe List" mode that saves your recipes you learn whenever your bag is full
(Currently it shows all recipes even if they aren't creatable from what's available on the floor, which I think is fine as the list will be short and you can set goals for repeat crafts without needing the items around; but should they have some indication they're not craftable yet?)
Added sort option so you can sort by Quality or by Name
(I would like to add a Sort by Ingredients in Bag, like put 7/8 recipes at the top, but that will need more work, right now the sort is just an array of item IDs that is basically constant)
Added a markup {{NoLineBreak}} that lets a line be as long as you want, used for item names in the recipe list at the moment for long item names to be forced onto one …

Learned Recipe List + name sort + misc crafting stuff

---

descriptions/ab+/en_us.lua
descriptions/rep/en_us.lua
features/eid_conditionals.lua
features/eid_conditionals_funcs.lua
features/eid_data.lua

This adds modder friendly addCondition functions to the top of the conditional functions file. (Kinda silly that I have an "addCondition" and "AddConditional" function in the same file but it's fine)
I haven't really added functions to be used by modders before, but I think these offer a good amount of simplicity and customization. I tested all the functions using The Sad Onion, should work the same as with actual modded items.
I also started work on Overridden by / Overrides conditions for some of the worst offenders. Very soon, I'll definitely need to work on a way to avoid having too many of the same type of condition display at once, and I'm thinking that because of how complex overridden/overrides can be, maybe it can have some kind of "z-ordering" type thing so it stops checking …

API functions for adding conditionals + override/overridden part 1

---

descriptions/ab+/en_us.lua
descriptions/rep/en_us.lua
features/eid_conditionals.lua
features/eid_conditionals_funcs.lua

I've added a lot more override/overridden lists for the top offending items.
With that, I added two ways to prevent redundant conditionals from displaying at once; a layer system (basically for these overrides where they mostly have a logical priority), and an ID system (for two items doing the exact same thing but having equal priority).
Things aren't perfect when you have a lot of items but it's definitely better than nothing. There are some truly bizarre multi-item priorities (Brimstone+Ludovico trumps C Section?) I ran into that would require more than a simple layer number to figure out what's active or not, maybe even simulating the game's code for how it figures this stuff out.

More override/overridden conditionals

---

descriptions/rep/en_us.lua
features/eid_api.lua
features/eid_modifiers.lua
main.lua

Added Glitched Crown support.
The way I've chosen to track the possible items is by watching every pedestal's current item ID and tracking the first and last time that ID was seen. Then, old IDs (like after a reroll) can be removed, and the items can be ordered properly.
The descriptions are toggled by pressing tab, which is a new control that has some new variables to support it.
I also went hard in supporting how it interacts with Spindown Dice and Flip.
I added an exception to allow pedestals to be described on the first frame they exist, which also improves Tainted Isaac's pedestal description experience, as they were blipping out of existence for one frame on switch before.

Glitched Crown support

---

descriptions/ab+/en_us.lua
descriptions/rep/en_us.lua
descriptions/rep/ko_kr.lua
features/eid_api.lua
features/eid_conditionals.lua
features/eid_conditionals_funcs.lua
features/eid_data.lua
features/eid_modifiers.lua

Multiple improvements to character info
Pocket item conditionals by biobak
New support for conditionals that only display when the character is the closest player; this will help single player display only relevant effects instead of having to append char-specific effects, while still being co-op friendly

"Health up" soul conditionals, pocket item conditionals

---

features/eid_mcm.lua

Big mod config menu update.
• Rewrote many names and descriptions to be clearer
• textInfos now all have periods at the end for consistency
• Trimmed down the General tab with the most used options left
• All options pertaining to descriptions being shown or hidden are now in Display
• All customizations (size, position, elements) for descriptions are now in Visuals
• Colorblind mode moved to the Colors tab
• Added a lot of subtabs to clean up the menus and make them easier to read
• Complex options moved to "advanced" subtabs in General and Crafting
• Fixed some overflowing text

MCM rewrite + reorg

---

descriptions/rep/en_us.lua

1. I found the duration for Strength? is 30 seconds
2. When the Tainted Jacob is caught by Dark Esau, the description of character 39 will be shown in the character info, so I think there should be some content.

en_us: fix the desc of card Strength? and add desc for Tainted Jacob's soul

---

features/eid_api.lua
main.lua

In EID, if the bullet point is an icon, the icon is left-aligned. This causes some odd behavior when displaying small icons like keys or coins in EID.
(In the image below, it is evident that the key icon is a bit too left.)
Especially when considering that the icons in the top-left corner of the game are center-aligned.
This PR adds a corresponding left offset for bullet point icons with smaller widths and no built-in left offset (so {{ArrowUp}} and {{Heart}} are unaffected), making them appear center-aligned rather than left-aligned.

Center the small bullet point icons

---

eid_config.lua
features/eid_api.lua
features/eid_mcm.lua
features/eid_modifiers.lua

- always check cycle with RGON 
- this allows soul of isaac or everything jar. still 5+ entries are needed to show summary list
- non RGON users still need Glitched Crown for cycle check (same as current)
- add option to disable summary list

Glitched Crown support additions

---

descriptions/rep+/spa.lua

translated and added the "wishing bone" and "Lunch bag" trinkets and the "void" item descriptions

Updated spanish translation for Rep+

---

descriptions/ab+/it.lua
descriptions/rep+/it.lua

As the title, mini monstro (id 471) was lacking a "{" in its starting interpolation. Just added it.

Fix interpolation in Mini Monstro ita translaton

---

main.lua

The description overlapped with the hearts and charge bar in rep+, so I lowered it 10 units which I think is pretty good

Lower description in Repentance+ to avoid overlapping

---

features/eid_api.lua
main.lua

- due to 1.9.7.11 patch, being exploits for full reroll effect (d4) are completely fixed, 'Show Last Pool' function is no longer viable for pedestals, can lead to show incorrect item pool when obtained.
- Was going to remove the function for Rep+, but decided to handle them from `descriptionObj.ItemPoolType` instead, to manage it dynamically later.

Moved 'ItemPoolType' data to 'descriptionObj'

---

descriptions/rep+/spa.lua

Changes to the REP+ file:
- Added item description for "Punching Bag"
- Added item description for "The Ludovico Technique"
- Added item description for "Clicker"
- Updated the item description of "Delirious"
- Added item description for  "Mars"
- Added item description for  "Star of Bethlehem"
- Added item description for  "Jar of Wisps"
- Added card description for "X - Wheel of Fortune"
- Added "tarotClothBuffs" description for "X - Wheel of Fortune"
- Added "horsepills" description for "Amnesia"
- Added "ConditionalDescs" for "Sharp Plug + Tainted Magdalene"
- Added "bookOfVirtuesWisps" description for "The Bean"
- Added "bookOfVirtuesWisps" description for "Kidney Bean"

spa: implemented 1.9.7.11 changes

---

features/eid_api.lua

- this callback is for modders who make unofficial language patches, since rep+ does not have any language support except English
- only works on rep v1.7.9b or higher

add EID_EVALUATE_AUTO_LANG callback

---

features/eid_data.lua
features/eid_itemprediction.lua
main.lua

We can just check the spike's variant and it'll always be a working sanguine bond spike. No need to assume room type and even if the player has the item.

Improve Sanguine Bond spike detection

---

features/eid_modifiers.lua

Fix for EID treating Mom's Box as a 3x multiplier for the purposes of additive values to things like Golden trinkets

Fix EID treating mom's box as a 3x multiplier for additive values for trinket boosts
